<!--
  - SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
  - SPDX-License-Identifier: AGPL-3.0-or-later
-->

<template>
	<div class="assistant-inputs">
		<div class="input-container">
			<div class="wrapper">
				<div class="col">
					<TaskTypeField
						field-key="origin_language"
						:field="translateTaskType.inputShape.origin_language"
						:value="inputs?.origin_language ?? null"
						:options="translateTaskType.inputShapeEnumValues.origin_language"
						:is-output="false"
						@update:value="onValueChange('origin_language', $event)" />
					<TaskTypeField
						field-key="input"
						:field="translateTaskType.inputShape.input"
						:value="inputs?.input ?? null"
						:is-output="false"
						@update:value="onValueChange('input', $event)" />
					<TaskTypeField v-if="showAdvanced"
						field-key="max_tokens"
						:field="translateTaskType.optionalInputShape.max_tokens"
						:value="inputs?.max_tokens ?? null"
						:is-output="false"
						@update:value="onValueChange('max_tokens', $event)" />
					<TaskTypeField v-if="showAdvanced"
						field-key="model"
						:field="translateTaskType.optionalInputShape.model"
						:value="inputs?.model ?? null"
						:options="translateTaskType.optionalInputShapeEnumValues.model"
						:is-output="false"
						@update:value="onValueChange('model', $event)" />
				</div>
				<div class="col">
					<TaskTypeField
						field-key="target_language"
						:field="translateTaskType.inputShape.target_language"
						:value="inputs?.target_language ?? null"
						:options="translateTaskType.inputShapeEnumValues.target_language"
						:is-output="false"
						@update:value="onValueChange('target_language', $event)" />
					<TaskTypeField
						field-key="output"
						:field="translateTaskType.outputShape.output"
						:value="outputs?.output ?? null"
						:is-output="true"
						@update:value="onOutputValueChange('output', $event)" />
					<NcNoteCard v-if="outputEqualsInput"
						class="warning-note"
						type="warning">
						{{ t('assistant', 'The task ran successfully but the result is identical to the input.') }}
					</NcNoteCard>
					<NcNoteCard v-else-if="hasInitialOutput"
						class="warning-note"
						type="warning">
						{{ t('assistant', 'This output was generated by AI. Make sure to double-check and adjust.') }}
					</NcNoteCard>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import NcNoteCard from '@nextcloud/vue/dist/Components/NcNoteCard.js'

import TaskTypeField from '../fields/TaskTypeField.vue'

export default {
	name: 'TranslateForm',

	components: {
		NcNoteCard,
		TaskTypeField,
	},

	props: {
		translateTaskId: {
			type: [Number, null],
			default: null,
		},
		translateTaskType: {
			type: Object,
			required: true,
		},
		inputs: {
			type: [Object, null],
			default: null,
		},
		outputs: {
			type: [Object, null],
			default: null,
		},
		showAdvanced: {
			type: Boolean,
			default: false,
		},
	},

	emits: [
		'update:inputs',
	],

	data() {
		return {
		}
	},

	computed: {
		outputEqualsInput() {
			if (typeof this.inputs?.input === 'string' && typeof this.outputs?.output === 'string') {
				return this.hasInitialOutput && this.outputs.output?.trim() === this.inputs.input?.trim()
			}
			return false
		},
		hasInitialOutput() {
			return !!this.outputs?.output?.trim()
		},
	},

	watch: {
		translateTaskType() {
			console.debug('[assistant] watch translateTaskType', this.translateTaskType, this.translateTaskTypeId)
			this.setDefaultValues(true)
		},
	},

	mounted() {
		console.debug('[assistant] mounted TranslateForm', this.translateTaskId, this.translateTaskType)
		// don't set the default values if there is a loaded task (initial or from history)
		if (this.translateTaskId === null) {
			this.setDefaultValues(false)
		}

		this.autosize()
	},

	methods: {
		autosize() {
			const inputField = document.getElementById('input-input')
			const outputField = document.getElementById('output-input')
			if (inputField && outputField) {
				inputField.style.overflowY = 'hidden'
				inputField.style.height = 'auto'
				const height = inputField.scrollHeight + 10
				inputField.style.height = height + 'px'
				outputField.style.height = height + 'px'
				inputField.style.overflowY = 'auto'
			}
		},
		onValueChange(key, value) {
			if (key === 'input') {
				this.autosize()
			}
			const newValues = {
				...this.inputs,
				[key]: value,
			}
			console.debug('[assistant] translate field value change', newValues)
			this.$emit('update:inputs', newValues)
		},
		onOutputValueChange(key, value) {
			const newValues = {
				...this.outputs,
				[key]: value,
			}
			console.debug('[assistant] translate output field value change', newValues)
			this.$emit('update:outputs', newValues)
		},
		setDefaultValues(clear = true) {
			console.debug('[assistant] set translate default values', this.translateTaskType?.inputShapeDefaults, this.translateTaskType?.optionalInputShapeDefaults)
			const inputs = clear
				? {}
				: {
					...this.inputs,
				}
			// set default values
			if (this.translateTaskType.inputShapeDefaults) {
				Object.keys(this.translateTaskType.inputShapeDefaults).forEach(key => {
					if (this.translateTaskType.inputShapeDefaults[key]) {
						inputs[key] = this.translateTaskType.inputShapeDefaults[key]
					}
				})
			}
			if (this.translateTaskType.optionalInputShapeDefaults) {
				Object.keys(this.translateTaskType.optionalInputShapeDefaults).forEach(key => {
					if (this.translateTaskType.optionalInputShapeDefaults[key]) {
						inputs[key] = this.translateTaskType.optionalInputShapeDefaults[key]
					}
				})
			}
			this.$emit('update:inputs', inputs)
		},
	},
}
</script>

<style lang="scss" scoped>
.assistant-inputs {
	margin-bottom: 1rem;

	.wrapper {
		display: grid;
		grid-template-columns: repeat(2, minmax(300px, 1fr));
		grid-column-gap: 16px;

		.col {
			grid-row: 1/2;
		}
	}

	:deep(.rich-contenteditable__input) {
		display: block;
		width: 100%;
		margin-bottom: 12px;
		height: auto;
		resize: none;
		box-sizing: border-box;
		overflow-y: auto;
		min-height: 62px;
		max-height: 58vh;
	}
}

@media (max-width: 670px) {
	.assistant-inputs {
		.wrapper {
			display: block;
		}

		:deep(.rich-contenteditable__input) {
			max-height: 20vh;
		}
	}
}
</style>
