<!--
SPDX-FileCopyrightText: Sami Finnilä <sami.finnila@nextcloud.com>
SPDX-License-Identifier: AGPL-3.0-or-later
-->
<template>
	<div class="assistant-picker-content-wrapper">
		<div class="assistant-picker-content">
			<h2>
				{{ t('assistant', 'AI text generation') }}
			</h2>
			<div class="input-wrapper">
				<NcTextField
					ref="assistant-search-input"
					:value.sync="query"
					:label="t('assistant', 'Enter your question or task here:')"
					placeholder="Generate a TODO list for a classic work day."
					:disabled="loading"
					:show-trailing-button="!!query"
					@keydown.enter="generate"
					@trailing-button-click="query = ''" />
			</div>
			<div v-if="result === null || query === ''"
				class="prompts">
				<NcUserBubble v-for="p in prompts"
					:key="p.id + p.value"
					class="prompt-bubble"
					:title="p.value"
					:size="30"
					avatar-image="icon-history"
					:display-name="p.value"
					@click="query = p.value" />
			</div>
			<div class="preview">
				<FreePromptGenerationDisplay v-if="genId !== null"
					:gen-id="genId"
					:result.sync="result"
					@error="onError"
					@loaded="onLoaded"
					@scheduled="scheduled = true" />
			</div>
			<div class="footer">
				<NcButton
					type="secondary"
					:aria-label="t('assistant', 'Preview text generation by AI')"
					:disabled="loading || !query"
					@click="generate">
					{{ previewButtonLabel }}
					<template #icon>
						<NcLoadingIcon v-if="loading" />
						<RefreshIcon v-else-if="result !== null" />
						<EyeIcon v-else />
					</template>
				</NcButton>
				<NcButton v-if="genId !== null && loading && scheduled"
					type="secondary"
					@click="notifyWhenReady">
					{{ t('assistant', 'Notify when ready') }}
					<template #icon>
						<ArrowRightIcon />
					</template>
				</NcButton>
				<NcButton v-if="result !== null"
					type="primary"
					:aria-label="t('assistant', 'Submit text generated by AI')"
					:disabled="loading || emptyResult"
					@click="submit">
					{{ t('assistant', 'Submit') }}
					<template #icon>
						<ArrowRightIcon />
					</template>
				</NcButton>
			</div>
		</div>
	</div>
</template>

<script>
import EyeIcon from 'vue-material-design-icons/Eye.vue'
import RefreshIcon from 'vue-material-design-icons/Refresh.vue'
import ArrowRightIcon from 'vue-material-design-icons/ArrowRight.vue'

import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
import NcTextField from '@nextcloud/vue/dist/Components/NcTextField.js'
import NcUserBubble from '@nextcloud/vue/dist/Components/NcUserBubble.js'

import FreePromptGenerationDisplay from '../../components/FreePrompt/FreePromptGenerationDisplay.vue'

import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { showError } from '@nextcloud/dialogs'

export default {
	name: 'FreePromptCustomPickerElement',

	components: {
		NcButton,
		NcLoadingIcon,
		NcTextField,
		ArrowRightIcon,
		NcUserBubble,
		RefreshIcon,
		EyeIcon,
		FreePromptGenerationDisplay,
	},

	props: {
		providerId: {
			type: String,
			required: true,
		},
		accessible: {
			type: Boolean,
			default: false,
		},
	},

	data() {
		return {
			query: '',
			genId: null,
			loading: false,
			error: false,
			models: [],
			completionNumber: 1,
			prompts: null,
			notify: false,
			submitted: false,
			result: null,
			scheduled: false,
		}
	},

	computed: {
		previewButtonLabel() {
			return this.result !== null
				? t('assistant', 'Regenerate')
				: t('assistant', 'Preview')
		},
		emptyResult() {
			return this.result.trim() === ''
		},
	},

	watch: {
	},

	mounted() {
		this.focusOnInput()
		this.getPromptHistory()
	},

	beforeDestroy() {
		if (!this.notify && !this.submitted) {
			this.cancelGeneration()
		}
	},

	methods: {
		focusOnInput() {
			setTimeout(() => {
				this.$refs['assistant-search-input'].$el.getElementsByTagName('input')[0]?.focus()
			}, 300)
		},
		getPromptHistory() {
			const params = {
				params: {
				},
			}
			const url = generateUrl('/apps/assistant/f/prompt_history')
			return axios.get(url, params)
				.then((response) => {
					this.prompts = response.data
				})
				.catch((error) => {
					console.error(error)
				})
		},
		submit() {
			this.submitted = true
			this.$emit('submit', this.result.trim())
		},
		onError() {
			this.error = true
			this.loading = false
			this.genId = null
		},
		onLoaded() {
			this.loading = false
		},
		insertPrompt(prompt) {
			if (this.prompts.find(p => p.value === prompt) === undefined) {
				this.prompts.unshift({
					id: 0,
					value: prompt,
				})
			}
		},
		generate() {
			if (this.query === '') {
				return
			}
			this.loading = true
			this.scheduled = false
			this.error = false
			this.result = null
			this.genId = null
			const params = {
				prompt: this.query,
				nResults: this.completionNumber,
			}
			const url = generateUrl('/apps/assistant/f/process_prompt')
			return axios.post(url, params)
				.then((response) => {
					const data = response.data
					if (data.length && data.length > 0) {
						this.genId = data

						this.insertPrompt(this.query)
					} else {
						this.error = response.data.error
					}
				})
				.catch((error) => {
					this.loading = false
					console.error('Text  completions request error', error)
					showError(
						t('assistant', 'Text generation error') + ': '
							+ (error.response?.data?.body?.error?.message
								|| error.response?.data?.body?.error?.code
								|| error.response?.data?.error
								|| t('assistant', 'Unknown text generation API error')
							),
					)
				})
		},
		cancelGeneration() {
			if (this.genId === null) {
				return
			}
			const params = {
				genId: this.genId,
			}
			const url = generateUrl('/apps/assistant/f/cancel_generation')
			return axios.post(url, params)
				.then((response) => {
					this.genId = null
					this.result = null
					this.loading = false
				})
				.catch((error) => {
					console.error('Text  completions request error', error)
					showError(
						t('assistant', 'Text generation error') + ': '
							+ (error.response?.data?.body?.error?.message
								|| error.response?.data?.body?.error?.code
								|| error.response?.data?.error
								|| t('assistant', 'Unknown text generation API error')
							),
					)
				})
		},
		notifyWhenReady() {
			/* For now all tasks will have a notification, since the assistant
			 * backend doesn't support omitting a notification, yet.
			 */
			this.notify = true
			this.$emit('submit', '')
			/* if (this.failed || this.genId === null) {
				return
			}

			const params = {
				genId: this.genId,
				notify: true,
			}
			const url = generateUrl('/apps/assistant/f/set_notify')
			axios.post(url, params)
				.then(() => {
					showMessage(t('assistant', 'You will be notified when the text generation is ready.'))
					this.notify = true
					this.$emit('submit', '')
				})
				.catch((error) => {
					console.error('Notify when ready request error', error)
					showError(
						t('assistant', 'Notify when ready error') + ': '
						+ (error.response?.data?.body?.error?.message
							|| error.response?.data?.body?.error?.code
							|| error.response?.data?.error
							|| t('assistant', 'Unknown notify when ready error')
						),
					)
				}) */
		},
	},
}
</script>

<style scoped lang="scss">
.assistant-picker-content-wrapper {
	width: 100%;
}

.assistant-picker-content {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding: 12px 16px 16px 16px;

	h2 {
		display: flex;
		align-items: center;
	}

	.prompts {
		margin-top: 8px;
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		> * {
			margin-right: 8px;
		}
	}

	.prompt-bubble {
		max-width: 250px;
	}

	.preview {
		width: 100%;
	}

	.spacer {
		flex-grow: 1;
	}

	.attribution {
		color: var(--color-text-maxcontrast);
		padding-bottom: 8px;
	}

	.input-wrapper {
		display: flex;
		align-items: center;
		width: 100%;
	}

	.prompt-select {
		width: 100%;
		margin-top: 4px;
	}

	.footer {
		width: 100%;
		display: flex;
		align-items: center;
		justify-content: end;
		margin-top: 12px;
		> * {
			margin-left: 4px;
		}
	}
}
</style>
