<template>
	<NcLoadingIcon v-if="loadingTaskTypes" />
	<NoProviderEmptyContent v-else-if="taskTypes.length === 0" />
	<div v-else
		class="assistant-form">
		<span class="assistant-bubble">
			<CreationIcon :size="16" class="icon" />
			<span>{{ t('assistant', 'Nextcloud Assistant') }}</span>
		</span>
		<TaskTypeSelect
			:value.sync="mySelectedTaskTypeId"
			class="task-custom-select"
			:inline="5"
			:options="sortedTaskTypes"
			@update:value="onTaskTypeUserChange" />
		<div v-if="showHistory"
			class="history">
			<div class="history--title">
				<NcButton
					class="history--back-button"
					type="secondary"
					:title="t('assistant', 'Back to the assistant')"
					@click="showHistory = false">
					<template #icon>
						<NcLoadingIcon v-if="historyLoading" />
						<ArrowLeftIcon v-else />
					</template>
				</NcButton>
				<h3 v-if="selectedTaskType">
					{{ t('assistant', 'Previous "{taskTypeName}" tasks', { taskTypeName: selectedTaskType.name }) }}
				</h3>
			</div>
			<TaskList
				class="history--list"
				:task-type="selectedTaskType"
				:loading.sync="historyLoading"
				@try-again="onHistoryTryAgain"
				@load-task="onHistoryLoadTask" />
		</div>
		<div v-else class="task-input-output-form">
			<h2 v-if="selectedTaskType"
				class="task-name">
				{{ selectedTaskType.name }}
			</h2>
			<span v-if="selectedTaskType"
				class="task-description">
				{{ selectedTaskType.description }}
			</span>
			<AssistantFormInputs v-if="selectedTaskType"
				:inputs.sync="myInputs"
				:selected-task-type="selectedTaskType" />
			<div v-if="hasOutput"
				class="output">
				<hr>
				<label
					for="assistant-output"
					class="output-title">
					{{ t('assistant', 'Result') }}
				</label>
				<TaskTypeFields
					class="output-fields"
					:is-output="true"
					:shape="selectedTaskType.outputShape"
					:optional-shape="selectedTaskType.optionalOutputShape ?? null"
					:values.sync="myOutputs" />
				<NcNoteCard v-if="outputEqualsInput"
					class="warning-note"
					type="warning">
					{{ t('assistant', 'The task ran successfully but the result is identical to the input.') }}
				</NcNoteCard>
				<NcNoteCard v-else-if="hasInitialOutput"
					class="warning-note"
					type="warning">
					{{ t('assistant', 'This output was generated by AI. Make sure to double-check and adjust.') }}
				</NcNoteCard>
			</div>
		</div>
		<!-- hide the footer for chatty-llm -->
		<div v-if="!showHistory && mySelectedTaskTypeId !== 'chatty-llm'" class="footer">
			<NcButton v-if="selectedTaskType"
				class="history-button"
				type="secondary"
				:aria-label="t('assistant', 'Show previous tasks')"
				@click="showHistory = true">
				<template #icon>
					<HistoryIcon />
				</template>
				{{ t('assistant', 'Previous "{taskTypeName}" tasks', { taskTypeName: selectedTaskType.name }) }}
			</NcButton>
			<div class="footer--action-buttons">
				<NcButton
					v-if="showSubmit"
					:type="submitButtonType"
					class="submit-button"
					:disabled="!canSubmit"
					:title="syncSubmitButtonTitle"
					@click="onSyncSubmit">
					{{ syncSubmitButtonLabel }}
					<template #icon>
						<NcLoadingIcon v-if="loading" />
						<CreationIcon v-else />
					</template>
				</NcButton>
				<NcButton
					v-for="(b, i) in actionButtonsToShow"
					:key="i"
					:type="b.type ?? 'secondary'"
					:title="b.title"
					@click="onActionButtonClick(b)">
					{{ b.label }}
					<template v-if="b.iconSvg" #icon>
						<NcIconSvgWrapper :svg="b.iconSvg" />
					</template>
				</NcButton>
			</div>
		</div>
	</div>
</template>

<script>
import ArrowLeftIcon from 'vue-material-design-icons/ArrowLeft.vue'
import CreationIcon from 'vue-material-design-icons/Creation.vue'
import HistoryIcon from 'vue-material-design-icons/History.vue'

import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcIconSvgWrapper from '@nextcloud/vue/dist/Components/NcIconSvgWrapper.js'
import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
import NcNoteCard from '@nextcloud/vue/dist/Components/NcNoteCard.js'

import AssistantFormInputs from './AssistantFormInputs.vue'
import NoProviderEmptyContent from './NoProviderEmptyContent.vue'
import TaskList from './TaskList.vue'
import TaskTypeSelect from './TaskTypeSelect.vue'
import TaskTypeFields from './fields/TaskTypeFields.vue'

import axios from '@nextcloud/axios'
import { generateOcsUrl, generateUrl } from '@nextcloud/router'
import Vue from 'vue'
import VueClipboard from 'vue-clipboard2'

Vue.use(VueClipboard)

const FREE_PROMPT_TASK_TYPE_ID = 'core:text2text'

export default {
	name: 'AssistantTextProcessingForm',
	components: {
		TaskTypeFields,
		NoProviderEmptyContent,
		TaskList,
		TaskTypeSelect,
		NcButton,
		NcLoadingIcon,
		NcIconSvgWrapper,
		CreationIcon,
		HistoryIcon,
		ArrowLeftIcon,
		NcNoteCard,
		AssistantFormInputs,
	},
	provide() {
		return {
			providedCurrentTaskId: () => this.selectedTaskId,
		}
	},
	props: {
		loading: {
			type: Boolean,
			default: false,
		},
		selectedTaskId: {
			type: [Number, null],
			default: null,
		},
		inputs: {
			type: Object,
			default: () => {},
		},
		outputs: {
			type: [Object, null],
			default: null,
		},
		selectedTaskTypeId: {
			type: [String, null],
			default: null,
		},
		actionButtons: {
			type: Array,
			default: () => [],
		},
	},
	emits: [
		'sync-submit',
		'action-button-clicked',
		'try-again',
		'load-task',
	],
	data() {
		return {
			myInputs: this.inputs,
			myOutputs: this.outputs,
			taskTypes: [],
			mySelectedTaskTypeId: this.selectedTaskTypeId || FREE_PROMPT_TASK_TYPE_ID,
			showHistory: false,
			loadingTaskTypes: false,
			historyLoading: false,
		}
	},
	computed: {
		selectedTaskType() {
			if (this.mySelectedTaskTypeId === null) {
				return null
			}
			return this.taskTypes.find(tt => tt.id === this.mySelectedTaskTypeId)
		},
		sortedTaskTypes() {
			return this.taskTypes.slice().sort((a, b) => {
				const prioA = a.priority
				const prioB = b.priority
				return prioA > prioB
					? 1
					: prioA < prioB
						? -1
						: 0
			})
		},
		submitButtonType() {
			return this.hasOutput ? 'secondary' : 'primary'
		},
		showSubmit() {
			return this.selectedTaskType
		},
		canSubmit() {
			if (this.selectedTaskType.id === 'speech-to-text') {
				return (this.myInputs.sttMode === 'record' && this.myInputs.audioData !== null)
					|| (this.myInputs.sttMode === 'choose' && this.myInputs.audioFilePath !== null)
			}
			// otherwise, check that none of the properties of myInputs are empty
			console.debug('[assistant] canSubmit', this.myInputs)
			if (Object.keys(this.myInputs).length === 0) {
				return false
			}
			const taskType = this.selectedTaskType
			return Object.keys(this.myInputs).every(k => {
				// optional input shape is not checked
				if (!Object.keys(taskType.inputShape).includes(k)) {
					return true
				}
				const v = this.myInputs[k]
				return (typeof v === 'string' && !!v?.trim())
					|| (typeof v === 'boolean')
					|| (typeof v === 'number')
					|| (typeof v === 'object' && !!v)
			})
				&& this.selectedTaskType
		},
		syncSubmitButtonLabel() {
			return this.hasOutput
				? t('assistant', 'Try again')
				: this.selectedTaskType.id === FREE_PROMPT_TASK_TYPE_ID
					? t('assistant', 'Send request')
					: this.selectedTaskType.name
		},
		syncSubmitButtonTitle() {
			return this.hasOutput
				? t('assistant', 'Launch this task again')
				: t('assistant', 'Launch a task')
		},
		hasInitialOutput() {
			return !!this.outputs?.output?.trim()
		},
		hasOutput() {
			return this.myOutputs
				&& Object.keys(this.myOutputs).length > 0
				&& Object.values(this.myOutputs).every(v => v !== null)
		},
		outputEqualsInput() {
			if (typeof this.inputs.input === 'string' && typeof this.outputs.output === 'string') {
				return this.hasInitialOutput && this.outputs?.output?.trim() === this.inputs.input?.trim()
			}
			return false
		},
		formattedOutput() {
			if (this.mySelectedTaskTypeId === 'OCP\\TextToImage\\Task') {
				return window.location.protocol + '//' + window.location.host + generateUrl('/apps/assistant/i/{imageGenId}', { imageGenId: this.myOutput })
			}
			return this.myOutput.trim()
		},
		actionButtonsToShow() {
			return this.hasOutput ? this.actionButtons : []
		},
	},
	watch: {
		outputs(newVal) {
			console.debug('update output in proc form', newVal)
			this.myOutputs = newVal
		},
		inputs(newVal) {
			this.myInputs = newVal
		},
		mySelectedTaskTypeId(newVal) {
			this.myOutputs = {}
		},
	},
	mounted() {
		this.getTaskTypes()
		console.debug('aaaa myoutputsss', this.myOutputs)
	},
	methods: {
		getTaskTypes() {
			this.loadingTaskTypes = true
			axios.get(generateOcsUrl('/apps/assistant/api/v1/task-types'))
				.then((response) => {
					this.taskTypes = response.data.ocs.data.types
				})
				.catch((error) => {
					console.error(error)
				})
				.then(() => {
					this.loadingTaskTypes = false
				})
		},
		onTaskTypeUserChange() {
			this.myOutputs = null
		},
		onSyncSubmit() {
			this.$emit('sync-submit', { inputs: this.myInputs, selectedTaskTypeId: this.mySelectedTaskTypeId })
		},
		onActionButtonClick(button) {
			this.$emit('action-button-clicked', { button, output: this.myOutputs })
		},
		onHistoryTryAgain(e) {
			this.showHistory = false
			this.$emit('try-again', e)
		},
		onHistoryLoadTask(e) {
			this.showHistory = false
			this.$emit('load-task', e)
		},
	},
}
</script>

<style lang="scss" scoped>
.assistant-form {
	//width: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: start;
	gap: 12px;
	overflow-y: auto;
	overflow-x: hidden;

	h2 {
		margin-top: 0;
	}

	.task-input-output-form {
		display: flex;
		flex-direction: column;
		width: 100%;
		// to make it max height, it will overflow anyway
		height: 100000px;
		overflow: auto;

		> * {
			margin-right: 6px;
		}
	}

	.output {
		display: flex;
		flex-direction: column;
		align-items: start;
		justify-content: center;

		.warning-note {
			align-self: normal;
		}

		hr {
			width: 100%;
		}

		.input-label {
			align-self: start;
			font-weight: bold;
		}
		.output-title {
			margin-top: 8px;
			font-size: 24px;
			font-weight: bold;
		}
		.output-fields {
			width: 100%;
		}
	}

	.assistant-bubble {
		align-self: start;
		display: flex;
		gap: 8px;
		background-color: var(--color-primary-element-light);
		border-radius: var(--border-radius-rounded);
		padding: 2px 8px;
		.icon {
			color: var(--color-primary);
		}
	}

	.task-custom-select {
		width: 100%;
	}

	.task-action-select {
		width: 100%;
	}

	.task-name {
		margin-bottom: 0px;
	}

	.task-name,
	.task-description {
		align-self: start;
	}

	.footer {
		width: 100%;
		display: flex;
		.history-button {
			height: 44px;
		}
		&--action-buttons {
			flex-grow: 1;
			display: flex;
			flex-wrap: wrap;
			justify-content: end;
			gap: 4px;
		}
	}

	.history {
		width: 100%;
		// to make it max height, it will overflow anyway
		height: 100000px;
		display: flex;
		flex-direction: column;
		align-items: end;
		overflow: auto;

		&--list {
			width: 100%;
			overflow: auto;
		}

		&--title {
			width: 100%;
			display: flex;
			align-items: center;
			gap: 8px;
			margin-bottom: 4px;
			h3 {
				margin-top: 0px;
				margin-bottom: 0px;
			}
		}
	}

	.success-icon {
		color: var(--color-success);
	}
}
</style>
