<template>
	<NcModal v-if="show"
		:size="modalSize"
		:can-close="false"
		class="assistant-modal"
		@close="onCancel">
		<div ref="modal_content"
			class="assistant-modal--wrapper">
			<div class="assistant-modal--content">
				<span class="assistant-bubble">
					<CreationIcon :size="16" class="icon" />
					<span>{{ t('assistant', 'Nextcloud Assistant') }}</span>
				</span>
				<h2>
					{{ taskTypeName }}
				</h2>
				<NcButton :aria-label="closeButtonLabel"
					:title="closeButtonTitle"
					type="tertiary"
					class="close-button"
					@click="onCancel">
					<template #icon>
						<CloseIcon />
					</template>
				</NcButton>
				<div v-if="myOutput"
					class="output">
					<label
						for="assistant-output"
						class="input-label">
						{{ t('assistant', 'Result') }}
					</label>
					<NcRichContenteditable
						id="assistant-output"
						ref="output"
						:value.sync="myOutput"
						class="editable-output"
						:multiline="true"
						:placeholder="t('assistant', 'Result')"
						:link-autocomplete="false" />
					<NcNoteCard
						class="warning-note"
						type="warning">
						{{ t('assistant', 'This output was generated by AI. Make sure to double-check and adjust.') }}
					</NcNoteCard>
				</div>
			</div>
		</div>
	</NcModal>
</template>

<script>
import CloseIcon from 'vue-material-design-icons/Close.vue'
import CreationIcon from 'vue-material-design-icons/Creation.vue'

import NcModal from '@nextcloud/vue/dist/Components/NcModal.js'
import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcRichContenteditable from '@nextcloud/vue/dist/Components/NcRichContenteditable.js'
import NcNoteCard from '@nextcloud/vue/dist/Components/NcNoteCard.js'

import { TASK_TYPES } from '../constants.js'

export default {
	name: 'AssistantPlainTextModal',
	components: {
		NcModal,
		NcButton,
		CloseIcon,
		NcRichContenteditable,
		NcNoteCard,
		CreationIcon,
	},
	props: {
		output: {
			type: String,
			default: '',
		},
		taskType: {
			type: [Number, null],
			default: null,
		},
	},
	emits: [
		'cancel',
	],
	data() {
		return {
			show: true,
			myOutput: this.output,
			closeButtonTitle: t('assistant', 'Close'),
			closeButtonLabel: t('assistant', 'Close Nextcloud Assistant'),
			modalSize: 'normal',
		}
	},
	computed: {
		taskTypeName() {
			switch (this.taskType) {
			case TASK_TYPES.text_generation:
				return t('assistant', 'Text Generation')
			case TASK_TYPES.image_generation:
				return t('assistant', 'Image Generation')
			case TASK_TYPES.speech_to_text:
				return t('assistant', 'Speech to Text')
			default:
				return t('assistant', 'Unknown Result Type')
			}
		},
	},
	mounted() {
		if (this.myOutput !== '') {
			this.$refs.output.focus()
		}
	},
	methods: {
		onCancel() {
			this.show = false
			this.$emit('cancel')
		},
		onCopy() {

		},
	},
}
</script>

<style lang="scss">
// this is to avoid scroll on the container and leave it to the result block
.assistant-modal .modal-container {
	display: flex !important;

	//&__content {
	//padding: 16px;
	//}
}
</style>

<style lang="scss" scoped>
.assistant-modal--wrapper {
	//width: 100%;
	padding: 16px;
	overflow-y: auto;
}

.assistant-modal--content {
	width: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	overflow-y: auto;

	> h2 {
		display: flex;
		margin: 12px 0 20px 0;
		.icon {
			margin-right: 8px;
		}
	}

	.editable-output {
		width: 100%;
		display: flex;
		flex-direction: column;
		align-items: start;
	}

	.assistant-bubble {
		align-self: start;
		display: flex;
		gap: 8px;
		background-color: var(--color-primary-element-light);
		border-radius: var(--border-radius-rounded);
		padding: 2px 8px;
		.icon {
			color: var(--color-primary);
		}
	}

	.close-button {
		position: absolute;
		top: 4px;
		right: 4px;
		// No border on hover
		&:hover {
			outline: none;
		}
	}
}
</style>
