<template>
	<div class="assistant-form">
		<span class="assistant-bubble">
			<CreationIcon :size="16" class="icon" />
			<span>{{ t('assistant', 'Nextcloud Assistant') }}</span>
		</span>
		<TaskTypeSelect
			:value.sync="mySelectedTaskTypeId"
			class="task-custom-select"
			:inline="3"
			:options="taskTypes" />
		<h2 v-if="selectedTaskType"
			class="task-name">
			{{ selectedTaskType.name }}
		</h2>
		<span v-if="selectedTaskType"
			class="task-description">
			{{ selectedTaskType.description }}
		</span>
		<label for="assistant-input"
			class="input-label">
			{{ t('assistant', 'Input') }}
		</label>
		<NcRichContenteditable
			id="assistant-input"
			:value.sync="myInput"
			class="editable-input"
			:multiline="true"
			:disabled="loading"
			:placeholder="t('assistant', 'Type some text')"
			:link-autocomplete="false" />
		<div v-if="myOutput"
			class="output">
			<label
				for="assistant-output"
				class="input-label">
				{{ t('assistant', 'Result') }}
			</label>
			<NcRichContenteditable
				id="assistant-output"
				ref="output"
				:value.sync="myOutput"
				class="editable-output"
				:multiline="true"
				:disabled="loading"
				:placeholder="t('assistant', 'Result')"
				:link-autocomplete="false" />
			<NcNoteCard
				class="warning-note"
				type="warning">
				{{ t('assistant', 'This output was generated by AI. Make sure to double-check and adjust.') }}
			</NcNoteCard>
		</div>
		<div class="footer">
			<NcButton
				v-if="showSubmit"
				:type="submitButtonType"
				class="submit-button"
				:disabled="!canSubmit"
				:title="t('assistant', 'Run a task')"
				@click="onSyncSubmit">
				{{ syncSubmitButtonLabel }}
				<template #icon>
					<NcLoadingIcon v-if="loading" />
					<CreationIcon v-else />
				</template>
			</NcButton>
			<!--NcButton
				v-if="showSubmit"
				:type="submitButtonType"
				class="submit-button"
				:disabled="!canSubmit"
				:aria-label="t('assistant', 'Schedule an assistant task')"
				:title="t('assistant', 'Schedule')"
				@click="onSubmit">
				{{ submitButtonLabel }}
				<template #icon>
					<CreationIcon />
				</template>
			</NcButton-->
			<NcButton
				v-if="hasOutput"
				type="primary"
				class="copy-button"
				:title="t('assistant', 'Copy output')"
				@click="onCopy">
				{{ t('assistant', 'Copy') }}
				<template #icon>
					<ClipboardCheckOutlineIcon v-if="copied" />
					<ContentCopyIcon v-else />
				</template>
			</NcButton>
			<div v-if="hasOutput"
				class="action-buttons">
				<NcButton
					v-for="(b, i) in actionButtons"
					:key="i"
					:type="b.type ?? 'secondary'"
					:title="b.title"
					@click="onActionButtonClick(b)">
					{{ b.label }}
					<template v-if="b.iconSvg" #icon>
						<NcIconSvgWrapper :svg="b.iconSvg" />
					</template>
				</NcButton>
			</div>
		</div>
	</div>
</template>

<script>
import ContentCopyIcon from 'vue-material-design-icons/ContentCopy.vue'
import ClipboardCheckOutlineIcon from 'vue-material-design-icons/ClipboardCheckOutline.vue'
import CreationIcon from 'vue-material-design-icons/Creation.vue'

import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcRichContenteditable from '@nextcloud/vue/dist/Components/NcRichContenteditable.js'
import NcNoteCard from '@nextcloud/vue/dist/Components/NcNoteCard.js'
import NcIconSvgWrapper from '@nextcloud/vue/dist/Components/NcIconSvgWrapper.js'

import TaskTypeSelect from './TaskTypeSelect.vue'

import axios from '@nextcloud/axios'
import { generateOcsUrl } from '@nextcloud/router'
import { showError } from '@nextcloud/dialogs'
import VueClipboard from 'vue-clipboard2'
import Vue from 'vue'

Vue.use(VueClipboard)

const FREE_PROMPT_TASK_TYPE_ID = 'OCP\\TextProcessing\\FreePromptTaskType'

export default {
	name: 'AssistantForm',
	components: {
		TaskTypeSelect,
		NcButton,
		NcRichContenteditable,
		NcLoadingIcon,
		NcIconSvgWrapper,
		CreationIcon,
		ContentCopyIcon,
		ClipboardCheckOutlineIcon,
		NcNoteCard,
	},
	props: {
		loading: {
			type: Boolean,
			default: false,
		},
		input: {
			type: String,
			default: '',
		},
		output: {
			type: String,
			default: '',
		},
		selectedTaskTypeId: {
			type: [String, null],
			default: null,
		},
		actionButtons: {
			type: Array,
			default: () => [],
		},
	},
	emits: [
		'sync-submit',
		'submit',
		'action-button-clicked',
	],
	data() {
		return {
			myInput: this.input,
			myOutput: this.output,
			taskTypes: [],
			mySelectedTaskTypeId: this.selectedTaskTypeId || FREE_PROMPT_TASK_TYPE_ID,
			copied: false,
		}
	},
	computed: {
		selectedTaskType() {
			if (this.mySelectedTaskTypeId === null) {
				return null
			}
			return this.taskTypes.find(tt => tt.id === this.mySelectedTaskTypeId)
		},
		submitButtonType() {
			return this.myOutput.trim() ? 'secondary' : 'primary'
		},
		showSubmit() {
			return this.selectedTaskType
		},
		canSubmit() {
			return this.selectedTaskType && !!this.myInput.trim()
		},
		submitButtonLabel() {
			return this.myOutput.trim()
				? t('assistant', 'Try again')
				: this.selectedTaskType.id === FREE_PROMPT_TASK_TYPE_ID
					? t('assistant', 'Send request')
					: this.selectedTaskType.name
		},
		syncSubmitButtonLabel() {
			return this.myOutput.trim()
				? t('assistant', 'Try again')
				: this.selectedTaskType.id === FREE_PROMPT_TASK_TYPE_ID
					? t('assistant', 'Send request')
					: this.selectedTaskType.name
		},
		hasOutput() {
			return !!this.myOutput.trim()
		},
	},
	watch: {
		output(newVal) {
			this.myOutput = newVal
		},
	},
	mounted() {
		this.getTaskTypes()
	},
	methods: {
		getTaskTypes() {
			axios.get(generateOcsUrl('textprocessing/tasktypes', 2))
				.then((response) => {
					this.taskTypes = response.data.ocs.data.types
				})
				.catch((error) => {
					console.error(error)
				})
		},
		onSubmit() {
			this.$emit('submit', { input: this.myInput.trim(), taskTypeId: this.mySelectedTaskTypeId })
		},
		onSyncSubmit() {
			this.$emit('sync-submit', { input: this.myInput.trim(), taskTypeId: this.mySelectedTaskTypeId })
		},
		async onCopy() {
			try {
				const container = this.$refs.output.$el
				await this.$copyText(this.myOutput.trim(), container)
				this.copied = true
				setTimeout(() => {
					this.copied = false
				}, 5000)
			} catch (error) {
				console.error(error)
				showError(t('assistant', 'Result could not be copied to clipboard'))
			}
		},
		onActionButtonClick(button) {
			this.$emit('action-button-clicked', { button, output: this.myOutput.trim() })
		},
	},
}
</script>

<style lang="scss" scoped>
.assistant-form {
	//width: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	gap: 12px;
	overflow-y: auto;

	.editable-input,
	.editable-output {
		width: 100%;
		min-height: unset !important;
		max-height: 200px !important;
	}

	.editable-input {
		min-height: 92px !important;
	}

	> .input-label {
		margin-bottom: -12px;
	}

	.input-label {
		align-self: start;
		font-weight: bold;
	}

	.output {
		width: 100%;
		display: flex;
		flex-direction: column;
		align-items: start;
	}

	.assistant-bubble {
		align-self: start;
		display: flex;
		gap: 8px;
		background-color: var(--color-primary-element-light);
		border-radius: var(--border-radius-rounded);
		padding: 2px 8px;
		.icon {
			color: var(--color-primary);
		}
	}

	.task-custom-select {
		width: 100%;
	}

	.task-action-select {
		width: 100%;
	}

	.task-name {
		margin-bottom: 0px;
	}

	.task-name,
	.task-description {
		align-self: start;
	}

	.footer {
		width: 100%;
		display: flex;
		flex-wrap: wrap;
		justify-content: end;
		gap: 4px;
		.action-buttons {
			display: flex;
			flex-wrap: wrap;
			justify-content: end;
			gap: 4px;
		}
	}

	.success-icon {
		color: var(--color-success);
	}

	.warning-note {
		align-self: normal;
	}
}
</style>
