<template>
	<NcLoadingIcon v-if="loadingTaskTypes" />
	<NoProviderEmptyContent v-else-if="taskTypes.length === 0" />
	<div v-else
		class="assistant-form">
		<span class="assistant-bubble">
			<CreationIcon :size="16" class="icon" />
			<span>{{ t('assistant', 'Nextcloud Assistant') }}</span>
		</span>
		<TaskTypeSelect
			:value.sync="mySelectedTaskTypeId"
			class="task-custom-select"
			:inline="5"
			:options="taskTypes"
			@update:value="onTaskTypeUserChange" />
		<div v-if="showHistory"
			class="history">
			<div class="history--title">
				<NcButton
					class="history--back-button"
					type="secondary"
					:title="t('assistant', 'Back to the assistant')"
					@click="showHistory = false">
					<template #icon>
						<NcLoadingIcon v-if="historyLoading" />
						<ArrowLeftIcon v-else />
					</template>
				</NcButton>
				<h3 v-if="selectedTaskType">
					{{ t('assistant', 'Previous "{taskTypeName}" tasks', { taskTypeName: selectedTaskType.name }) }}
				</h3>
			</div>
			<TaskList
				class="history--list"
				:task-type="selectedTaskType"
				:loading.sync="historyLoading"
				@try-again="onHistoryTryAgain"
				@load-task="onHistoryLoadTask" />
		</div>
		<div v-else class="task-input-output-form">
			<h2 v-if="selectedTaskType"
				class="task-name">
				{{ selectedTaskType.name }}
			</h2>
			<span v-if="selectedTaskType"
				class="task-description">
				{{ selectedTaskType.description }}
			</span>
			<AssistantFormInputs
				:inputs.sync="myInputs"
				:selected-task-type-id="mySelectedTaskTypeId" />
			<div v-if="myOutput !== null"
				class="output">
				<label
					for="assistant-output"
					class="input-label">
					{{ t('assistant', 'Result') }}
				</label>
				<div v-if="mySelectedTaskTypeId === 'OCP\\TextToImage\\Task'"
					ref="output">
					<a :href="formattedOutput" class="external">{{ formattedOutput }}</a>
					<Text2ImageDisplay
						:image-gen-id="myOutput" />
				</div>
				<NcRichContenteditable v-else
					id="assistant-output"
					ref="output"
					:value.sync="myOutput"
					class="editable-output"
					:multiline="true"
					:disabled="loading"
					:placeholder="t('assistant', 'Result')"
					:link-autocomplete="false" />
				<NcNoteCard v-if="outputEqualsInput"
					class="warning-note"
					type="warning">
					{{ t('assistant', 'The task ran successfully but the result is identical to the input.') }}
				</NcNoteCard>
				<NcNoteCard v-else-if="hasInitialOutput"
					class="warning-note"
					type="warning">
					{{ t('assistant', 'This output was generated by AI. Make sure to double-check and adjust.') }}
				</NcNoteCard>
				<NcNoteCard v-else
					class="warning-note"
					type="warning">
					{{ t('assistant', 'The task ran successfully but the generated text is empty.') }}
				</NcNoteCard>
			</div>
			<!-- hide the footer for chatty-llm -->
			<div v-if="mySelectedTaskTypeId !== 'chatty-llm'" class="footer">
				<NcButton v-if="selectedTaskType"
					class="history-button"
					type="secondary"
					:aria-label="t('assistant', 'Show previous tasks')"
					@click="showHistory = true">
					<template #icon>
						<HistoryIcon />
					</template>
					{{ t('assistant', 'Previous "{taskTypeName}" tasks', { taskTypeName: selectedTaskType.name }) }}
				</NcButton>
				<div class="footer--action-buttons">
					<NcButton
						v-if="showSubmit"
						:type="submitButtonType"
						class="submit-button"
						:disabled="!canSubmit"
						:title="t('assistant', 'Run a task')"
						@click="onSyncSubmit">
						{{ syncSubmitButtonLabel }}
						<template #icon>
							<NcLoadingIcon v-if="loading" />
							<CreationIcon v-else />
						</template>
					</NcButton>
					<NcButton
						v-if="hasOutput"
						type="primary"
						class="copy-button"
						:title="t('assistant', 'Copy output')"
						@click="onCopy">
						{{ t('assistant', 'Copy') }}
						<template #icon>
							<ClipboardCheckOutlineIcon v-if="copied" />
							<ContentCopyIcon v-else />
						</template>
					</NcButton>
					<NcButton
						v-for="(b, i) in actionButtonsToShow"
						:key="i"
						:type="b.type ?? 'secondary'"
						:title="b.title"
						@click="onActionButtonClick(b)">
						{{ b.label }}
						<template v-if="b.iconSvg" #icon>
							<NcIconSvgWrapper :svg="b.iconSvg" />
						</template>
					</NcButton>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import ArrowLeftIcon from 'vue-material-design-icons/ArrowLeft.vue'
import ClipboardCheckOutlineIcon from 'vue-material-design-icons/ClipboardCheckOutline.vue'
import ContentCopyIcon from 'vue-material-design-icons/ContentCopy.vue'
import CreationIcon from 'vue-material-design-icons/Creation.vue'
import HistoryIcon from 'vue-material-design-icons/History.vue'

import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcIconSvgWrapper from '@nextcloud/vue/dist/Components/NcIconSvgWrapper.js'
import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
import NcNoteCard from '@nextcloud/vue/dist/Components/NcNoteCard.js'
import NcRichContenteditable from '@nextcloud/vue/dist/Components/NcRichContenteditable.js'

import AssistantFormInputs from './AssistantFormInputs.vue'
import NoProviderEmptyContent from './NoProviderEmptyContent.vue'
import TaskList from './TaskList.vue'
import TaskTypeSelect from './TaskTypeSelect.vue'
import Text2ImageDisplay from './Text2Image/Text2ImageDisplay.vue'

import axios from '@nextcloud/axios'
import { showError } from '@nextcloud/dialogs'
import { generateOcsUrl, generateUrl } from '@nextcloud/router'
import Vue from 'vue'
import VueClipboard from 'vue-clipboard2'

Vue.use(VueClipboard)

const FREE_PROMPT_TASK_TYPE_ID = 'OCP\\TextProcessing\\FreePromptTaskType'

export default {
	name: 'AssistantTextProcessingForm',
	components: {
		NoProviderEmptyContent,
		TaskList,
		Text2ImageDisplay,
		TaskTypeSelect,
		NcButton,
		NcRichContenteditable,
		NcLoadingIcon,
		NcIconSvgWrapper,
		CreationIcon,
		ContentCopyIcon,
		ClipboardCheckOutlineIcon,
		HistoryIcon,
		ArrowLeftIcon,
		NcNoteCard,
		AssistantFormInputs,
	},
	props: {
		loading: {
			type: Boolean,
			default: false,
		},
		inputs: {
			type: Object,
			default: () => {},
		},
		output: {
			type: [String, null],
			default: null,
		},
		selectedTaskTypeId: {
			type: [String, null],
			default: null,
		},
		actionButtons: {
			type: Array,
			default: () => [],
		},
	},
	emits: [
		'sync-submit',
		'submit',
		'action-button-clicked',
		'try-again',
		'load-task',
	],
	data() {
		return {
			myInputs: this.inputs,
			myOutput: this.output,
			taskTypes: [],
			mySelectedTaskTypeId: this.selectedTaskTypeId || FREE_PROMPT_TASK_TYPE_ID,
			copied: false,
			showHistory: false,
			loadingTaskTypes: false,
			historyLoading: false,
		}
	},
	computed: {
		selectedTaskType() {
			if (this.mySelectedTaskTypeId === null) {
				return null
			}
			return this.taskTypes.find(tt => tt.id === this.mySelectedTaskTypeId)
		},
		submitButtonType() {
			return this.hasOutput ? 'secondary' : 'primary'
		},
		showSubmit() {
			return this.selectedTaskType
		},
		canSubmit() {
			if (this.selectedTaskType.id === 'speech-to-text') {
				return (this.myInputs.sttMode === 'record' && this.myInputs.audioData !== null)
					|| (this.myInputs.sttMode === 'choose' && this.myInputs.audioFilePath !== null)
			}
			// otherwise, check that none of the properties of myInputs are empty
			return Object.values(this.myInputs).every(v => {
				return (typeof v === 'string' && !!v?.trim())
					|| (typeof v === 'boolean')
					|| (typeof v === 'number')
					|| (typeof v === 'object' && !!v)
			})
				&& this.selectedTaskType
		},
		syncSubmitButtonLabel() {
			return this.hasOutput
				? t('assistant', 'Try again')
				: this.selectedTaskType.id === FREE_PROMPT_TASK_TYPE_ID
					? t('assistant', 'Send request')
					: this.selectedTaskType.name
		},
		hasInitialOutput() {
			return !!this.output?.trim()
		},
		hasOutput() {
			return !!this.myOutput?.trim()
		},
		outputEqualsInput() {
			return this.hasInitialOutput && this.output?.trim() === this.inputs.prompt?.trim()
		},
		formattedOutput() {
			if (this.mySelectedTaskTypeId === 'OCP\\TextToImage\\Task') {
				return window.location.protocol + '//' + window.location.host + generateUrl('/apps/assistant/i/{imageGenId}', { imageGenId: this.myOutput })
			}
			return this.myOutput.trim()
		},
		actionButtonsToShow() {
			return this.hasOutput ? this.actionButtons : []
		},
	},
	watch: {
		output(newVal) {
			this.myOutput = newVal
		},
		inputs(newVal) {
			this.myInputs = newVal
		},
	},
	mounted() {
		this.getTaskTypes()
	},
	methods: {
		getTaskTypes() {
			this.loadingTaskTypes = true
			axios.get(generateOcsUrl('/apps/assistant/api/v1/task-types'))
				.then((response) => {
					this.taskTypes = response.data.ocs.data.types
				})
				.catch((error) => {
					console.error(error)
				})
				.then(() => {
					this.loadingTaskTypes = false
				})
		},
		onTaskTypeUserChange() {
			this.myOutput = null
		},
		onSubmit() {
			this.$emit('submit', { inputs: this.myInputs, selectedTaskTypeId: this.mySelectedTaskTypeId })
		},
		onSyncSubmit() {
			this.$emit('sync-submit', { inputs: this.myInputs, selectedTaskTypeId: this.mySelectedTaskTypeId })
		},
		async onCopy() {
			try {
				const container = this.$refs.output.$el ?? this.$refs.output
				await this.$copyText(this.formattedOutput, container)
				this.copied = true
				setTimeout(() => {
					this.copied = false
				}, 5000)
			} catch (error) {
				console.error(error)
				showError(t('assistant', 'Result could not be copied to clipboard'))
			}
		},
		onActionButtonClick(button) {
			this.$emit('action-button-clicked', { button, output: this.formattedOutput })
		},
		onHistoryTryAgain(e) {
			this.showHistory = false
			this.$emit('try-again', e)
		},
		onHistoryLoadTask(e) {
			this.showHistory = false
			this.$emit('load-task', e)
		},
	},
}
</script>

<style lang="scss" scoped>
.assistant-form {
	//width: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	gap: 12px;
	overflow-y: auto;
	overflow-x: hidden;

	.task-input-output-form {
		display: flex;
		flex-direction: column;
		width: 100%;
		overflow: auto;
	}

	.output {
		width: 96%;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		margin-right: 16px;
		margin-left: 16px;
		.editable-output {
			width: 100%;
			:deep(.rich-contenteditable__input) {
				max-height: 300px !important;
			}
		}

		.warning-note {
			align-self: normal;
		}

		.input-label {
			align-self: start;
			font-weight: bold;
		}
	}

	.assistant-bubble {
		align-self: start;
		display: flex;
		gap: 8px;
		background-color: var(--color-primary-element-light);
		border-radius: var(--border-radius-rounded);
		padding: 2px 8px;
		.icon {
			color: var(--color-primary);
		}
	}

	.task-custom-select {
		width: 100%;
	}

	.task-action-select {
		width: 100%;
	}

	.task-name {
		margin-bottom: 0px;
	}

	.task-name,
	.task-description {
		align-self: start;
	}

	.footer {
		width: 100%;
		display: flex;
		.history-button {
			height: 44px;
		}
		&--action-buttons {
			flex-grow: 1;
			display: flex;
			flex-wrap: wrap;
			justify-content: end;
			gap: 4px;
		}
	}

	.history {
		width: 100%;
		display: flex;
		flex-direction: column;
		align-items: end;

		&--list {
			width: 100%;
		}

		&--title {
			width: 100%;
			display: flex;
			align-items: center;
			gap: 8px;
			h3 {
				margin-top: 0px;
				margin-bottom: 0px;
			}
		}
	}

	.success-icon {
		color: var(--color-success);
	}
}
</style>
