<!--
  - SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
  - SPDX-License-Identifier: AGPL-3.0-or-later
-->
<template>
	<div class="output">
		<ContextChatOutputForm v-if="selectedTaskTypeId === 'context_chat:context_chat'"
			class="output-fields"
			:output-shape="selectedTaskType.outputShape"
			:output="outputs" />
		<ContextChatSearchOutputForm v-else-if="selectedTaskTypeId === 'context_chat:context_chat_search'"
			class="output-fields"
			:output-shape="selectedTaskType.outputShape"
			:output="outputs" />
		<TaskTypeFields v-else
			class="output-fields"
			:is-output="true"
			:shape="selectedTaskType.outputShape"
			:optional-shape="selectedTaskType.optionalOutputShape ?? null"
			:shape-options="selectedTaskType.outputShapeEnumValues ?? null"
			:optional-shape-options="selectedTaskType.optionalOutputShapeEnumValues ?? null"
			:values="outputs"
			:show-advanced="showAdvanced"
			@update:values="$emit('update:outputs', $event)"
			@update:show-advanced="$emit('update:show-advanced', $event)" />
		<NcNoteCard v-if="outputEqualsInput"
			class="warning-note"
			type="warning">
			{{ t('assistant', 'The task ran successfully but the result is identical to the input.') }}
		</NcNoteCard>
		<NcNoteCard v-else-if="hasInitialOutput"
			class="warning-note"
			type="warning">
			{{ t('assistant', 'This output was generated by AI. Make sure to double-check and adjust.') }}
		</NcNoteCard>
	</div>
</template>

<script>
import NcNoteCard from '@nextcloud/vue/components/NcNoteCard'

import ContextChatOutputForm from './ContextChat/ContextChatOutputForm.vue'
import ContextChatSearchOutputForm from './ContextChat/ContextChatSearchOutputForm.vue'
import TaskTypeFields from './fields/TaskTypeFields.vue'

export default {
	name: 'AssistantFormOutputs',

	components: {
		ContextChatOutputForm,
		ContextChatSearchOutputForm,
		TaskTypeFields,
		NcNoteCard,
	},

	props: {
		inputs: {
			type: Object,
			default: () => {},
		},
		outputs: {
			type: Object,
			default: () => {},
		},
		selectedTaskType: {
			type: [Object, null],
			default: null,
		},
		showAdvanced: {
			type: Boolean,
			default: false,
		},
	},

	emits: [
		'update:outputs',
		'update:show-advanced',
	],

	computed: {
		selectedTaskTypeId() {
			return this.selectedTaskType?.id ?? null
		},
		outputEqualsInput() {
			if (typeof this.inputs?.input === 'string' && typeof this.outputs?.output === 'string') {
				return this.hasInitialOutput && this.outputs.output?.trim() === this.inputs.input?.trim()
			}
			return false
		},
		hasInitialOutput() {
			if (typeof this.outputs?.output === 'string') {
				return !!this.outputs.output?.trim()
			}
			return false
		},
	},
}

</script>

<style lang="scss" scoped>
.output {
	margin-top: 24px;
	display: flex;
	flex-direction: column;
	align-items: start;
	justify-content: center;

	.warning-note {
		align-self: normal;
	}

	hr {
		width: 100%;
	}

	.input-label {
		align-self: start;
		font-weight: bold;
	}
	.output-fields {
		width: 100%;
	}
}
</style>
