<template>
	<div class="text2image-picker-content-wrapper">
		<div class="text2image-picker-content">
			<h2>
				{{ t('assistant', 'AI image generation') }}
			</h2>
			<div class="input-wrapper">
				<NcTextField ref="text2image-search-input"
					:value.sync="query"
					:label="inputPlaceholder"
					placeholder=""
					:disabled="loading"
					:show-trailing-button="!!query"
					@keydown.enter="generate"
					@trailing-button-click="query = ''" />
			</div>
			<div v-if="result === null || query === ''" class="prompts">
				<NcUserBubble v-for="p in prompts"
					:key="p.id + p.value"
					class="prompt-bubble"
					:title="p.value"
					:size="30"
					avatar-image="icon-history"
					:display-name="p.value"
					@click="query = p.value" />
			</div>
			<div v-if="result !== null" class="preview-container">
				<h3>{{ t('assistant', 'Preview') }}</h3>
				<div class="image-preview">
					<Text2ImageDisplay :key="result.image_gen_id"
						:image-gen-id="result.image_gen_id"
						@failed="imageGenerationFailed"
						@ready="imageGenerationReady"
						@processing="imageGenerationIsProcessing" />
				</div>
			</div>
			<div class="footer">
				<div class="buttons">
					<NcButton type="secondary"
						:aria-label="t('assistant', 'Preview image generation by AI')"
						:disabled="loading || !query"
						@click="generate">
						{{ previewButtonLabel }}
						<template #icon>
							<NcLoadingIcon v-if="loading" />
							<RefreshIcon v-else-if="result !== null" />
							<EyeIcon v-else />
						</template>
					</NcButton>
					<NcButton v-if="result !== null"
						type="secondary"
						:disabled="!isGenerating"
						@click="notifyWhenReady">
						{{ t('assistant', 'Notify when ready') }}
						<template #icon>
							<ArrowRightIcon />
						</template>
					</NcButton>
					<NcButton v-if="result !== null"
						type="primary"
						:aria-label="t('assistant', 'Submit image(s) generated by AI')"
						:disabled="loading || emptyResult"
						@click="submit">
						{{ t('assistant', 'Send') }}
						<template #icon>
							<ArrowRightIcon />
						</template>
					</NcButton>
				</div>
				<NcButton class="advanced-button"
					type="tertiary"
					:aria-label="t('assistant', 'Show/hide advanced options')"
					@click="showAdvanced = !showAdvanced">
					<template #icon>
						<component :is="showAdvancedIcon" />
					</template>
					{{ t('assistant', 'Advanced options') }}
				</NcButton>
			</div>
			<div v-show="showAdvanced" class="advanced">
				<div class="line">
					<NcCheckboxRadioSwitch class="include-query"
						:checked.sync="displayPrompt">
						{{ t('assistant', 'Include the prompt in the result') }}
					</NcCheckboxRadioSwitch>
				</div>
				<div class="spacer" />
				<div class="line">
					<label for="nResults">{{ t('assistant', 'Number of results') }}</label>
					<input id="nResults"
						v-model="nResults"
						type="number"
						min="1"
						max="10">
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import EyeIcon from 'vue-material-design-icons/Eye.vue'
import RefreshIcon from 'vue-material-design-icons/Refresh.vue'
import ArrowRightIcon from 'vue-material-design-icons/ArrowRight.vue'

import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
import NcTextField from '@nextcloud/vue/dist/Components/NcTextField.js'
import NcCheckboxRadioSwitch from '@nextcloud/vue/dist/Components/NcCheckboxRadioSwitch.js'
import NcUserBubble from '@nextcloud/vue/dist/Components/NcUserBubble.js'
import ChevronRightIcon from 'vue-material-design-icons/ChevronRight.vue'
import ChevronDownIcon from 'vue-material-design-icons/ChevronDown.vue'

import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { showError, showMessage } from '@nextcloud/dialogs'

import Text2ImageDisplay from '../../components/Text2Image/Text2ImageDisplay.vue'

export default {
	name: 'Text2ImageCustomPickerElement',

	components: {
		NcButton,
		NcLoadingIcon,
		NcTextField,
		NcCheckboxRadioSwitch,
		ArrowRightIcon,
		NcUserBubble,
		RefreshIcon,
		EyeIcon,
		Text2ImageDisplay,
	},

	props: {
		providerId: {
			type: String,
			required: true,
		},
		accessible: {
			type: Boolean,
			default: false,
		},
	},

	data() {
		return {
			query: '',
			result: null,
			loading: false,
			isGenerating: false,
			models: [],
			inputPlaceholder: t('assistant', 'A description of the image you want to generate'),
			displayPrompt: true,
			notify: false,
			prompts: null,
			submitted: false,
			nResults: 1,
			showAdvanced: false,
		}
	},

	computed: {
		previewButtonLabel() {
			return this.result !== null
				? t('assistant', 'Regenerate')
				: t('assistant', 'Preview')
		},
		emptyResult() {
			return this.result === null || this.result.length === 0
		},
		showAdvancedIcon() {
			return this.showAdvanced
				? ChevronDownIcon
				: ChevronRightIcon
		},
	},

	watch: {
		displayPrompt(newValue) {
			localStorage.setItem('text2image_display_prompt', JSON.stringify(newValue))
		},
	},

	mounted() {
		this.focusOnInput()
		this.getPromptHistory()
		const cachedValue = localStorage.getItem('text2image_display_prompt') === 'true'
		if (cachedValue !== null) {
			this.displayPrompt = cachedValue
		}
	},

	beforeDestroy() {
		if (!this.submitted && !this.notify) {
			this.cancelGeneration()
		}
	},

	methods: {
		focusOnInput() {
			setTimeout(() => {
				this.$refs['text2image-search-input'].$el.getElementsByTagName('input')[0]?.focus()
			}, 300)
		},
		getPromptHistory() {
			const params = {
				params: {
				},
			}
			const url = generateUrl('/apps/assistant/i/prompt_history')
			return axios.get(url, params)
				.then((response) => {
					this.prompts = response.data
				})
				.catch((error) => {
					console.error(error)
				})
		},
		submit() {
			this.submitted = true
			this.$emit('submit', this.result.reference_url)
		},
		insertPrompt(prompt) {
			if (this.prompts.find(p => p.value === prompt) === undefined) {
				this.prompts.unshift({
					id: 0,
					value: prompt,
				})
			}
		},
		cancelGeneration() {
			if (this.result === null) {
				return
			}
			const url = generateUrl('/apps/assistant/i/cancel_generation')
			axios.post(url, { imageGenId: this.result.image_gen_id })
				.catch((error) => {
					console.error('Image generation cancel request error', error)
					showError(
						t('assistant', 'Image generation cancel error') + ': '
						+ (error.response?.data?.body?.error?.message
							|| error.response?.data?.body?.error?.code
							|| error.response?.data?.error
							|| t('assistant', 'Unknown image generation cancel error')
						),
					)
				})
			this.result = null
		},
		generate() {

			if (this.result !== null) {
				this.cancelGeneration()
			}

			if (this.query === '') {
				return
			}

			this.loading = true

			const params = {
				appId: 'assistant',
				identifier: '',
				prompt: this.query,
				nResults: this.nResults,
				displayPrompt: this.displayPrompt,
			}
			const url = generateUrl('/apps/assistant/i/process_prompt')
			return axios.post(url, params)
				.then((response) => {
					const data = response.data
					if (data?.url !== undefined) {
						this.result = data
						this.insertPrompt(this.query)
					} else {
						showError(t('assistant', 'Unexpected response from server.'))
					}
				})
				.catch((error) => {
					console.error('Image generation request error', error)
					showError(
						t('assistant', 'Image generation error') + ': '
						+ (error.response?.data?.body?.error?.message
							|| error.response?.data?.body?.error?.code
							|| error.response?.data?.error
							|| t('assistant', 'Unknown image generation error')
						),
					)
				})
				.then(() => {
					this.loading = false
				})
		},
		notifyWhenReady() {
			if (this.failed || this.result === null) {
				return
			}
			const url = generateUrl('/apps/assistant/i/notify/' + this.result.image_gen_id)
			axios.post(url)
				.then(() => {
					showMessage(t('assistant', 'You will be notified when the image generation is ready.'))
					this.notify = true
					this.$emit('submit', '')
				})
				.catch((error) => {
					console.error('Notify when ready request error', error)
					showError(
						t('assistant', 'Notify when ready error') + ': '
						+ (error.response?.data?.body?.error?.message
							|| error.response?.data?.body?.error?.code
							|| error.response?.data?.error
							|| t('assistant', 'Unknown notify when ready error')
						),
					)
				})
		},
		imageGenerationFailed() {
			this.isGenerating = false
		},
		imageGenerationReady() {
			this.isGenerating = false
		},
		imageGenerationIsProcessing() {
			this.isGenerating = true
		},
	},
}
</script>

<style scoped lang="scss">
.text2image-picker-content-wrapper {
	width: 100%;
}

.text2image-picker-content {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding: 12px 16px 16px 16px;

	h2 {
		display: flex;
		align-items: center;
	}

	.prompts {
		margin-top: 8px;
		display: flex;
		flex-wrap: wrap;
		align-items: center;

		>* {
			margin-right: 8px;
		}
	}

	.prompt-bubble {
		max-width: 250px;
	}

	.preview-container {
		width: 100%;

		.image-preview {
			display: flex;
			flex-direction: column;
			margin-top: 8px;
			border: 3px solid var(--color-border);
			border-radius: var(--border-radius-large);
			padding: 12px;
			width: 100%;
		}
	}

	.spacer {
		flex-grow: 1;
	}
	.input-wrapper {
		display: flex;
		align-items: center;
		width: 100%;
	}

	.prompt-select {
		width: 100%;
		margin-top: 4px;
	}

	.footer {
		width: 100%;
		display: flex;
		flex-direction: row-reverse;
		margin-top: 12px;
		justify-content: space-between;

		.buttons {
			display: flex;
			align-items: end;

			>* {
				margin-left: 4px;
			}
		}
	}

	.advanced {
		width: 100%;
		padding: 12px 0;
		.line {
			display: flex;
			align-items: center;
			margin-top: 8px;

			input,
			select {
				margin-left: 24px;
				width: 200px;
			}
		}

		input[type=number] {
			width: 80px;
			appearance: initial !important;
			-moz-appearance: initial !important;
			-webkit-appearance: initial !important;
		}
	}
}
</style>
